# docker-compose.yml
version: "3.7"

services:
  php-fpm:
    build: .docker/php-fpm
    container_name: poc-php-fpm
    working_dir: /application
    environment:
      DATABASE_URL: "mysql://poc:poc@mysql_db:3306/mercure_poc"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
    volumes:
      - .:/application/
    networks:
      - poc_mercure

  php-worker:
    build: .docker/php-worker
    container_name: poc-php-worker
    working_dir: /application
    environment:
      DATABASE_URL: "mysql://poc:poc@mysql_db:3306/mercure_poc"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
    volumes:
      - .:/application/
    networks:
      - poc_mercure

  nginx:
    build: .docker/nginx
    container_name: poc-nginx
    working_dir: /application
    volumes:
      - .:/application/
    ports:
      - "8080:80"
    networks:
      - poc_mercure

  mysql_db:
    image: 'mysql:latest'
    container_name: poc-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercure_poc
      MYSQL_USER: poc
      MYSQL_PASSWORD: poc
    ports:
      - '3306:3306'
    networks:
      - poc_mercure

  caddy:
    image: dunglas/mercure
    container_name: poc-mercure-hub
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      DEBUG: "debug"
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_JWT_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.Ws4gtnaPtM-R2-z9DnH-laFu5lDZrMnmyTpfU8uKyQo
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
        anonymous
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "9000:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - poc_mercure

volumes:
  caddy_data:
  caddy_config:

networks:
  poc_mercure: