# docker-compose.yml
version: "3.7"

services:
  mysql_db:
    image: 'mysql:latest'
    container_name: poc-mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mercure_poc
        MYSQL_USER: poc
        MYSQL_PASSWORD: poc
    ports:
      - '3306:3306'

  caddy:
    image: dunglas/mercure
    container_name: poc-mercure-hub
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS
      DEBUG: "debug"
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      MERCURE_JWT_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdLCJzdWJzY3JpYmUiOlsiKiJdfX0.Xh6y8YQ22OCv3ikYTEgFJH4I9opNv06toUyYlaYKtyA
      MERCURE_EXTRA_DIRECTIVES: |-
        cors_origins *
        anonymous
    # Uncomment the following line to enable the development mode
    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "9000:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
